### ISSUE TITLE
Add some screenshots of this app to readme.md

### ISSUE THREAD

**Issue by shivanshsoni** [shivanshsoni/MoviesLibrary2#2]

**Comment by Brennaleker** [comment]
Hello, I'd like to work on this task

**Comment by shivanshsoni** [comment]
Go ahead @Brennaleker

**Comment by Brennaleker** [comment]
@shivanshsoni I'm playing with the app in Android studio and after typing in the name of the movie and selecting a category there is no clear path forward. Am I missing something? see: [screenshot](https://imgur.com/a/bfPtd)

**Comment by shivanshsoni** [comment]
Ya, you are missing the small black coloured tick..[.screenshot](https://imgur.com/a/NSvna).. you can fix this to make it visible.
