### ISSUE TITLE
Reduce size of screenshots in readme to make it more attractive

### ISSUE THREAD

**Issue by shivanshsoni** [shivanshsoni/MoviesLibrary2#20]

**Comment by GaruGaru** [comment]
hi, I'd like to work on this 👍

**Comment by shivanshsoni** [comment]
Ok go ahead.... :)

**Comment by ungps** [comment]
I've already done it; need permision to push.

**Comment by dpescatore** [comment]
I'm working on it. I'm going to do a pull request right now.

**Comment by ungps** [comment]
Done pull request.

**Comment by saideepd** [comment]
@shivanshsoni I would like to take this up. And by reducing the screenshot size, you mean it's height & width right ?
