### ISSUE TITLE
Make any changes in the UI of this app to make it more attractive.

### ISSUE THREAD

**Issue by shivanshsoni** [shivanshsoni/MoviesLibrary2#3]

**Comment by hasansidd** [comment]
Would a recyclerview be better for this then a list view? Maybe in the future to pull posters, etc

**Comment by shivanshsoni** [comment]
ya sure .... go ahead..:)

**Comment by yutianlin** [comment]
I was thinking that the editing of a movie would be best handled on a longclick whereas additional info could be displayed on an itemclick (such as when movie was released, a picture of it, when it was last watched, or for a TV drama what episode they are on, etc.) What do you think @shivanshsoni ?

**Comment by shivanshsoni** [comment]
OK go ahead.... :) @yutianlin
