### ISSUE TITLE
Any new functionality in app is welcome

### ISSUE THREAD

**Issue by shivanshsoni** [shivanshsoni/MoviesLibrary2#4]

**Comment by dimivrn** [comment]
Hello, should i apply some new functionality in project?

**Comment by shivanshsoni** [comment]
yes,  you can add....

**Comment by yutianlin** [comment]
I was wondering what new functionalities you are adding @dimivrn

**Comment by dimivrn** [comment]
I added the functionality for inserting a summary for movie along with the title and genre.

**Comment by AnkitaKhurana** [comment]
There was some malapropism in the new features added recently in the project.
The Genre was confused for Gender. I have fixed the same.
Kindly review.

https://github.com/shivanshsoni/MoviesLibrary2/pull/34
